### ISSUE TITLE
LUA error

### ISSUE THREAD

**Issue by kiltotake** [blooblahguy/BigDumbLootCouncil#10]
Had this error for past week. Tried to reinstall. Still happening

`Message: attempt to concatenate a boolean value
Time: 01/10/18 21:46:24
Count: 8
Stack: attempt to concatenate a boolean value
Interface\SharedXML\SharedBasicControls.lua:208: in function <Interface\SharedXML\SharedBasicControls.lua:207>
[C]: ?
[C]: in function `strjoin'
Interface\AddOns\bigdumblootcouncil\functions.lua:116: in function `sendAction'
Interface\AddOns\bigdumblootcouncil\frames.lua:131: in function <Interface\AddOns\bigdumblootcouncil\frames.lua:100>
Interface\AddOns\bigdumblootcouncil\frames.lua:781: in function <Interface\AddOns\bigdumblootcouncil\frames.lua:780>

Locals: errorMessage = "attempt to concatenate a boolean value"
DisplayMessageInternal = <function> defined @Interface\SharedXML\SharedBasicControls.lua:191
MESSAGE_TYPE_ERROR = 0
`

**Comment by gladelynch** [comment]
This will be fixed in the release 2.25 which will show up shortly. I had
made this fix last week, but I guess I never made a release afterwards.
Thanks for the heads up
