### ISSUE TITLE
Lua error

### ISSUE THREAD

**Issue by Ramurotand** [blooblahguy/BigDumbLootCouncil#11]
Here's the screenshot.  This is using version 2.25.  I had just clicked to send loot to a person and that was successful, but this pops up afterwards.  It was longer then the window so you get beginning and ending of lua error with some overlap.

Part one:
https://imgur.com/EUycys8

Part two:
https://imgur.com/f2DrN1c

**Comment by Ramurotand** [comment]
The changes you made to core.lua on github (but haven't pushed out yet to everyone) has removed the lua errors associated with this issue when I tested it this past week when using your modified version from here.

**Comment by gladelynch** [comment]
Thanks for documenting this, I must have forgotten to build a release for it. It's now updated for everyone else
