### ISSUE TITLE
lua error 2.32 version

### ISSUE THREAD

**Issue by Takkero** [blooblahguy/BigDumbLootCouncil#13]
Date: 2018-08-16 22:13:05
ID: 8
Error occured in: Global
Count: 1
Message: ..\AddOns\bigdumblootcouncil\core.lua line 871:
   attempt to call method 'IsInRaidGroup' (a nil value)

**Comment by gladelynch** [comment]
Did this persist after you restarted your game? I'm not able to replicate as this function definitely exists.

**Comment by gladelynch** [comment]
This is resolved in last release, closing!
