### ISSUE TITLE
Frame Title Persists After Session

### ISSUE THREAD

**Issue by Cistoran** [blooblahguy/BigDumbLootCouncil#2]
If a session is started and you pass/roll all the items, the title on the frame persists until you reload.

https://gyazo.com/b1664c37cc8e398d12b65b8b73b248e8

**Comment by Cistoran** [comment]
Message: Interface\AddOns\bigdumblootcouncil\core.lua:303: attempt to concatenate local 'itemLink' (a nil value) Time: 12/16/17 21:46:01 Count: 5 Stack: Interface\AddOns\bigdumblootcouncil\core.lua:303: attempt to concatenate local 'itemLink' (a nil value) Interface\SharedXML\SharedBasicControls.lua:208: in function <Interface\SharedXML\SharedBasicControls.lua:207> [C]: ? Interface\AddOns\bigdumblootcouncil\core.lua:303: in function `removeUserConsidering' Interface\AddOns\bigdumblootcouncil\core.lua:924: in function <Interface\AddOns\bigdumblootcouncil\core.lua:748>  Locals: errorMessage = "Interface\AddOns\bigdumblootcouncil\core.lua:303: attempt to concatenate local 'itemLink' (a nil value)" DisplayMessageInternal = <function> defined @Interface\SharedXML\SharedBasicControls.lua:1 MESSAGE_TYPE_ERROR = 0

**Comment by gladelynch** [comment]
Do you have any other LUA errors? The lua errors should have pages you can cycle through for unique errors.

**Comment by Cistoran** [comment]
Only one of our raid members received the error and that's the only one they gave me. I'll see if we can replicate it again tonight and try to get more.

**Comment by gladelynch** [comment]
My recent push should stop most if not all the lua error, but everyone will need to update again.

**Comment by gladelynch** [comment]
Confirming that this is fixed with guild raid
