### ISSUE TITLE
Opening config

### ISSUE THREAD

**Issue by oayorkshireman** [blooblahguy/BigDumbLootCouncil#25]
Just installed through Wowup
Opened config using /bblc config and got this error

"Message: ...e\AddOns\BigDumbLootCouncil\config\config_frames.lua:199: BDLC Config_votes_input:CreateFontString(): Couldn't find inherited node "bdConfig_font"
Time: Fri Jul 30 20:05:21 2021
Count: 1
Stack: ...e\AddOns\BigDumbLootCouncil\config\config_frames.lua:199: BDLC Config_votes_input:CreateFontString(): Couldn't find inherited node "bdConfig_font"
[string "=[C]"]: ?
[string "=[C]"]: in function `CreateFontString'
[string "@Interface\AddOns\BigDumbLootCouncil\config\config_frames.lua"]:199: in function `createEdit'
[string "@Interface\AddOns\BigDumbLootCouncil\config\config.lua"]:99: in function <...nterface\AddOns\BigDumbLootCouncil\config\config.lua:58>
[string "=[C]"]: in function `SetShown'
[string "@Interface\AddOns\BigDumbLootCouncil\core\init.lua"]:170: in function `?'
[string "@Interface\FrameXML\ChatFrame.lua"]:5157: in function `ChatEdit_ParseText'
[string "@Interface\FrameXML\ChatFrame.lua"]:4821: in function `ChatEdit_SendText'
[string "@Interface\FrameXML\ChatFrame.lua"]:4857: in function <Interface\FrameXML\ChatFrame.lua:4853>
[string "=[C]"]: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals: "

Tried removing and downloading manually. Have same error.
Should i try without any other addons open?

Thanks 
Adam

**Comment by oayorkshireman** [comment]
With no addons activated but bdlc i get this 
"Message: ...e\AddOns\BigDumbLootCouncil\config\config_frames.lua:199: BDLC Config_votes_input:CreateFontString(): Couldn't find inherited node "bdConfig_font"
Time: Fri Jul 30 20:09:56 2021
Count: 1
Stack: ...e\AddOns\BigDumbLootCouncil\config\config_frames.lua:199: BDLC Config_votes_input:CreateFontString(): Couldn't find inherited node "bdConfig_font"
[string "=[C]"]: in function `CreateFontString'
[string "@Interface\AddOns\BigDumbLootCouncil\config\config_frames.lua"]:199: in function `createEdit'
[string "@Interface\AddOns\BigDumbLootCouncil\config\config.lua"]:99: in function <...nterface\AddOns\BigDumbLootCouncil\config\config.lua:58>
[string "=[C]"]: in function `SetShown'
[string "@Interface\AddOns\BigDumbLootCouncil\core\init.lua"]:170: in function `?'
[string "@Interface\FrameXML\ChatFrame.lua"]:5157: in function `ChatEdit_ParseText'
[string "@Interface\FrameXML\ChatFrame.lua"]:4821: in function `ChatEdit_SendText'
[string "@Interface\FrameXML\ChatFrame.lua"]:4857: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals: (*temporary) = BDLC Config_votes_input {
 0 = <userdata>
 OnBackdropLoaded = <function> defined @Interface\SharedXML\Backdrop.lua:205
 Center = <unnamed> {
 }
 GetBackdropColor = <function> defined @Interface\SharedXML\Backdrop.lua:443
 SetupTextureCoordinates = <function> defined @Interface\SharedXML\Backdrop.lua:267
 OnBackdropSizeChanged = <function> defined @Interface\SharedXML\Backdrop.lua:235
 HasBackdropInfo = <function> defined @Interface\SharedXML\Backdrop.lua:331
 SetBackdropBorderColor = <function> defined @Interface\SharedXML\Backdrop.lua:475
 RightEdge = <unnamed> {
 }
 backdropInfo = <table> {
 }
 BottomEdge = <unnamed> {
 }
 GetEdgeSize = <function> defined @Interface\SharedXML\Backdrop.lua:241
 BottomLeftCorner = <unnamed> {
 }
 BottomRightCorner = <unnamed> {
 }
 TopEdge = <unnamed> {
 }
 ApplyBackdrop = <function> defined @Interface\SharedXML\Backdrop.lua:347
 SetBackdrop = <function> defined @Interface\SharedXML\Backdrop.lua:382
 ClearBackdrop = <function> defined @Interface\SharedXML\Backdrop.lua:335
 TopRightCorner = <unnamed> {
 }
 GetBackdropBorderColor = <function> defined @Interface\SharedXML\Backdrop.lua:462
 GetBackdrop = <function> defined @Interface\SharedXML\Backdrop.lua:400
 TopLeftCorner = <unnamed> {
 }
 SetupPieceVisuals = <function> defined @Interface\SharedXML\Backdrop.lua:299
 SetBackdropColor = <function> defined @Interface\SharedXML\Backdrop.lua:452
 LeftEdge = <unnamed> {
 }
 SetBorderBlendMode = <function> defined @Interface\SharedXML\Backdrop.lua:319
}
(*temporary) = nil
(*temporary) = "OVERLAY"
(*temporary) = "bdConfig_font"
"

**Comment by gladelynch** [comment]
This is fixed in newest update
