### ISSUE TITLE
Multiple Sessions Moves Frame Off Screen

### ISSUE THREAD

**Issue by Cistoran** [blooblahguy/BigDumbLootCouncil#3]
If you run multiple sessions in a row (ex, when clearing a raid and doing multiple bosses), and don't reload UI between sessions, eventually the frame gets pushed off the screen and cannot be used.

**Comment by gladelynch** [comment]
The reason this is happening is because there is a LUA error that is stopping the script from continueing to run the repositions frame function. Please type /console scriptErrors 1 and /reload and copy and BDLC lua errors you get here.

**Comment by gladelynch** [comment]
Confirming that this is fixed with guild raid
