### ISSUE TITLE
give items, second open loot

### ISSUE THREAD

**Issue by Bumberek** [blooblahguy/BigDumbLootCouncil#4]
Can't give items to players choosen. I have windows when click on name yes/no but button yes no work.
When loot was incident close and open another time loot from boss people who roll have to do this second time and another when repeat.
After sesion and bigdumps label visible like on other inssues screen.

Add someting like block test when in raid group when you haven't assinst or leader.

**Comment by gladelynch** [comment]
The reason this is happening is because there is a LUA error that is stopping the script from continuing to run. Please type /console scriptErrors 1 and /reload and copy and BDLC lua errors you get here.

**Comment by gladelynch** [comment]
Confirming that this is fixed in most recent build

**Comment by Bumberek** [comment]
now is problem when award items all sension become end.

2017-12-20 18:10 GMT+01:00 blooblahguy <notifications@github.com>:
